// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import CoreBluetooth;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class BKBlukiiDescription;
@class CBCharacteristic;
@class NSError;


/// @class      BKProfileHandlerTemplate
///
/// BKProfileHandlerTemplate implements a template for a genralized handling of profile interaction. It implements the redirection of the forwarded callbacks to the appropriate methods and a mechanism which determines wheter an instance can handle a callback for a given characteristic based on information, provied by the subclass. It also implements a mechanism to resolve a pair of a Servic UUID and a Characteristic UUID to a CBCharacteristic.
///
/// If you want to implement a new BKProfileHandler by extending this template you need to override the following methods:
///
/// <ul><li>handleDidUpdateValueForCharacteristic:error:</li><li>handleDidWriteValueForCharacteristic:error:</li><li>handleDidUpdateSubscriptionForCharacteristic:error:</li></ul>
/// Furthermore you need to provide information about the characteristics your class can handle by overriding the internal methods in the topic 'Supported Characteristics'.
///
/// In your custom profile handler you should keep a certain terminology that is used in all existing profile handlers. The following table shows the frameworks equivalent term for the Core Bluetooth terms:
///
/// |   Core Bluetooth          |       BlukiiKit Profile Handler                   |
/// |===========================|===================================================|
/// | readValue                 | update{YOUR_CHARACTERISTIC_NAME}                  |
/// |---------------------------|---------------------------------------------------|
/// | writeValue                | change{YOUR_CHARACTERISTIC_NAME}To                |
/// |---------------------------|---------------------------------------------------|
/// | setNotifyValue  TRUE      | subscribeTo{YOUR_CHARACTERISTIC_NAME}             |
/// |---------------------------|---------------------------------------------------|
/// | setNotifyValue  FALSE     | unsubscribeFrom{YOUR_CHARACTERISTIC_NAME}         |
/// |---------------------------|---------------------------------------------------|
///
/// One exception of that terminology could be if there is a set of distinct values you can write to characteristic, like e.g. an enabler characteristic that takes numeric value for true and false.
/// In such a case you should give the methods names that explain what you are going to do with the characteristic by writing the value to it.
/// A good example is the enabler characteristic from the BKEnableableProfileHandlerTemplate subclasses. The methods that write a value to the enabler characteristic are named "enableProfile" and "disableProfile".
///
/// THIS IS CLASS IS INTENDED FOR THE INTERNAL USE IN THAT FRAMEWORK ONLY. DO NOT TRY TO CREATE AN INSTANCE OF THIS CLASS. THE INTERNAL TEMPLATE METHODS WILL RAISE AN FATAL ERROR IF YOU TRY TO HANDLE AN PERIPHERAL CALLBACK WITH AN INSTANCE OF THIS CLASS.
///
/// @seealso    BKEnableableProfileHandlerTemplate
SWIFT_CLASS("_TtC9blukiiKit24BKProfileHandlerTemplate")
@interface BKProfileHandlerTemplate : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull handlerType;
+ (NSString * _Nonnull)handlerTypeOfClass;
- (nonnull instancetype)initWithBlukii:(BKBlukiiDescription * _Nonnull)blukii OBJC_DESIGNATED_INITIALIZER;
- (BOOL)canHandleDidUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic;
- (void)handleDidUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (BOOL)canHandleDidWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic;
- (void)handleDidWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (BOOL)canHandleDidUpdateSubscriptionForCharacteristic:(CBCharacteristic * _Nonnull)characteristic;
- (void)handleDidUpdateSubscriptionForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
@end



/// @class  BKEnableableProfileHandlerTemplate
///
/// The BKEnableableProfileHandlerTemplate class is a subclass of BKProfileHandlerTemplate and implements the handling of the enabler characteristic for all profiles, that need to be enabled.
/// Concrete subclasses only need to provide the Service UUID and the Characteristic UUID of the appropriate enabler characteristic.
///
/// THIS IS CLASS IS INTENDED FOR THE INTERNAL USE IN THAT FRAMEWORK ONLY. DO NOT TRY TO CREATE AN INSTANCE OF THIS CLASS. THE INTERNAL TEMPLATE METHODS WILL RAISE AN FATAL ERROR IF YOU TRY TO HANDLE AN PERIPHERAL CALLBACK WITH AN INSTANCE OF THIS CLASS.
SWIFT_CLASS("_TtC9blukiiKit34BKEnableableProfileHandlerTemplate")
@interface BKEnableableProfileHandlerTemplate : BKProfileHandlerTemplate
- (void)handleDidUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidUpdateSubscriptionForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;

/// @method     enableProfile:
///
/// Writes the appropriate value to enable the profile to the enabler characteristic.
///
/// @param      completion  The BKProfileOperationCompletion that shall be called on completion of the writing.
- (void)enableProfile:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;

/// @method     disableProfile:
///
/// Writes the appropriate value to disable the profile to the enabler characteristic.
///
/// @param      completion  The BKProfileOperationCompletion that shall be called on completion of the writing.
- (void)disableProfile:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;

/// @method     updateEnabler:
///
/// Reads the value of the enabler characteristic.
///
/// @param      completion  The BKProfileOperationCompletion that shall be called on completion of the read.
- (void)updateEnabler:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;

/// @method     subscribeToEnabler:callOnNotify:
///
/// Sets the notify value for the enabler characteristic to true.
///
/// @param      completion  The BKProfileOperationCompletion that shall be called on completion of the notifcation value update.
///
/// @param      onNotify    The BKProfileOperationCompletion that shall be called when the characteristic sends a notification with the updated value.
- (void)subscribeToEnabler:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;

/// @method     unsubscribeFromEnabler:
///
/// Sets the notify value for the enabler characteristic to false.
///
/// @param      completion  The BKProfileOperationCompletion that shall be called on completion of the notifcation value update.
- (void)unsubscribeFromEnabler:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (nonnull instancetype)initWithBlukii:(BKBlukiiDescription * _Nonnull)blukii OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9blukiiKit29BKAccelerometerProfileHandler")
@interface BKAccelerometerProfileHandler : BKEnableableProfileHandlerTemplate
- (void)handleDidUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidUpdateSubscriptionForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)updateRange:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateXValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToXValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotifiy;
- (void)unsubscribeFromXValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateYValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToYValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotifiy;
- (void)unsubscribeFromYValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateZValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToZValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotifiy;
- (void)unsubscribeFromZValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateFilter:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)changeFilterTo:(uint16_t)filter completion:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateEventConfig:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateEventMode:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateEventState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)activateAccelerationMonitoring:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)deactivateAccelerationMonitoring:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToEventState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromEventState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateSwitchSense:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)changeSwitchSenseTo:(uint8_t)value completion:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateSwitchState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)activateSwitch:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)deactivateSwitch:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToSwitchState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotifiy;
- (void)unsubscribeFromSwitchState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (nonnull instancetype)initWithBlukii:(BKBlukiiDescription * _Nonnull)blukii OBJC_DESIGNATED_INITIALIZER;
@end

@class CBPeripheral;
@class BKBlukiiDeviceContext;
@class CBService;


/// @class      BKProfileLoaderTemplate
///
/// This class implements a template for a genralized discovery process. You can use this template to implement your own profile loaders or to discover a certain set of GATT services and characteristics. All you need to do is to override the internal methods below in the topic 'Template Methods'. The BKProfileLoaderTemplate will do the following steps to discover the concrete profile:
///
/// <ul><li>At first it will be checked wheter the given blukii is supported by comparing the device information. If these information are not available yet in the given BKBlukiiDescription they will be determined my the BKProfileLoaderTemplate.</li><li>The next step is to check which of the specified services are not yet discoverd.</li><li>After the discovery of the missing services the BKProfileLoaderTemplate will check for each service what characteristics are not yet discovered and will discover the missing ones.</li><li>If everything succeeded the BKProfileLoaderTemplate will add the BKProfileHandler instance, provided by the concrete subclass of BKProfileLoaderTemplate, to the BKBlukiiDeviceContext, associated with the BKBlukiiDescription. If there is no BKBlukiiDeviceContext a new one will be crearted with the current BKBlukiiDescription.</li></ul>
/// To subclass this template all you need to do is to provide the following information:
///
/// <ul><li>The minimum firmware revision</li><li>The services, that shall be discovered</li><li>For each service to discover the characteristic, that shall be discovered.</li><li>A instance of BKProfileHandler, that is responsible for handling the interaction with the loaded profile.</li></ul>
/// THIS IS CLASS IS INTENDED FOR THE INTERNAL USE IN THAT FRAMEWORK ONLY. DO NOT TRY TO CREATE AN INSTANCE OF THIS CLASS. THE INTERNAL TEMPLATE METHODS WILL RAISE AN FATAL ERROR IF YOU TRY TO LOAD A PROFILE WITH AN INSTANCE OF THIS CLASS.
SWIFT_CLASS("_TtC9blukiiKit23BKProfileLoaderTemplate")
@interface BKProfileLoaderTemplate : NSObject <CBPeripheralDelegate>
+ (BKBlukiiDescription * _Nullable)evaluatePeripheral:(CBPeripheral * _Nonnull)peripheral;
- (void)loadProfileForBlukii:(BKBlukiiDescription * _Nonnull)blukii completeWith:(void (^ _Nonnull)(BKBlukiiDeviceContext * _Nullable blukiiDeviceContext, NSError * _Nullable error))completion;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverServices:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



/// @class  BKAccelerometerProfileLoader
///
/// A concrete BKProfileLoader to load the Accelerometer profile.
SWIFT_CLASS("_TtC9blukiiKit28BKAccelerometerProfileLoader")
@interface BKAccelerometerProfileLoader : BKProfileLoaderTemplate
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9blukiiKit25BKAltimeterProfileHandler")
@interface BKAltimeterProfileHandler : BKEnableableProfileHandlerTemplate
- (void)handleDidUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidUpdateSubscriptionForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)updateMode:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateEventConfig:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateEventState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToEventState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotifiy:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromEventState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)changeSubscriptionValueForValueCharacteristic:(BOOL)value completion:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion onNotify:(void (^ _Nullable)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)changeSubscriptionValueForEventStateCharacteristic:(BOOL)value completion:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion onNotify:(void (^ _Nullable)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (nonnull instancetype)initWithBlukii:(BKBlukiiDescription * _Nonnull)blukii OBJC_DESIGNATED_INITIALIZER;
@end



/// @class  BKLightProfileLoader
///
/// A concrete BKProfileLoader to load the Light profile.
SWIFT_CLASS("_TtC9blukiiKit24BKAltimeterProfileLoader")
@interface BKAltimeterProfileLoader : BKProfileLoaderTemplate
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9blukiiKit30BKBatteryServiceProfileHandler")
@interface BKBatteryServiceProfileHandler : BKProfileHandlerTemplate
- (void)updateBatteryLevel:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)handleDidUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidUpdateSubscriptionForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (nonnull instancetype)initWithBlukii:(BKBlukiiDescription * _Nonnull)blukii OBJC_DESIGNATED_INITIALIZER;
@end



/// @class  BKBatteryServiceProfileLoader
///
/// A concrete BKProfileLoader to load the Battery Service profile.
SWIFT_CLASS("_TtC9blukiiKit29BKBatteryServiceProfileLoader")
@interface BKBatteryServiceProfileLoader : BKProfileLoaderTemplate
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class BKFirmwareRevision;


/// @class      BKBlukiiDescription
///
/// The BKBlukiiDescription class represents the information from the Device Info Profile of blukii, given as a CBPeripheral object. If the underlying characteristics have not been read yet, these information must be retrieved asynchronously using the method determineDeviceInformation:completion:.
///
/// BKBlukiiDescription also provides the possibility to check wheter a given CBPeripheral is a blukii device, using its advertising data. See isBlukiiDevice:
SWIFT_CLASS("_TtC9blukiiKit19BKBlukiiDescription")
@interface BKBlukiiDescription : NSObject <CBPeripheralDelegate>

/// @property   name
///
/// Represents the local device name of the encapsulated CBPeripheral.
@property (nonatomic, copy) NSString * _Nonnull name;

/// @property   peripheral
///
/// The CBPeripheral, that was usesd to instantiate the object
@property (nonatomic, readonly, strong) CBPeripheral * _Nonnull peripheral;

/// @property   firmwareRevisionString
///
/// A String containing the current firmware revision of the blukii. Only available after calling determineDeviceInformation:
///
/// @see        determineDeviceInformation:
@property (nonatomic, readonly, copy) NSString * _Nullable firmwareRevisionString;

/// @property   firmwareRevision
///
/// The current firmware revision of the blukii as a BKFirmwareRevision object. Only available after calling determineDeviceInformation:
///
/// @see        determineDeviceInformation:
@property (nonatomic, readonly, strong) BKFirmwareRevision * _Nullable firmwareRevision;

/// @property   hardwareRevision
///
/// A String containing the current hardware revision of the blukii. Only available after calling
///
/// @see        determineDeviceInformation:
@property (nonatomic, readonly, copy) NSString * _Nullable hardwareRevision;

/// @property   manufacterName
///
/// A String containing the manufacter name of the blukii. Only available after calling
///
/// @see        determineDeviceInformation:
@property (nonatomic, readonly, copy) NSString * _Nullable manufacterName;

/// @method     isBlukiiDevice:
///
/// Determines wheter a given CBPeripheral is a blukii device by using the local device name.
///
/// @param      peripheral  The CBPeripheral, that shall be checked
+ (BOOL)isBlukiiDevice:(CBPeripheral * _Nonnull)peripheral;

/// Creates a new instance with a given connected CBPeripheral.
///
/// @param      peripheral  The peripheral, that shall be used to initialize the instance.
///
/// @attention  Throws an exception if the given peripheral is not a blukii or the state is not .Connected. Use the function isBlukiiDevice: to check whether a peripheral represents a blukii or not.
///
/// @see        isBlukiiDevice:
/// @seealso    CBPeripheralState
- (nonnull instancetype)initWithPeripheral:(CBPeripheral * _Nonnull)peripheral OBJC_DESIGNATED_INITIALIZER;

/// @method     determineDeviceInformation:
///
/// Determines the device information of the encapsulated CBPeripheral.
///
/// @param      completion  A BKDeviceInfoDeterminationCompletion that shall be called upon the completion of the determination process.
///
/// @see        BKDeviceInfoDeterminationCompletion
- (void)determineDeviceInformationWithCompleteWith:(void (^ _Nonnull)(NSError * _Nullable error))completion;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverServices:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
@end

@class BKServiceProfileHandler;
@class BKRecordingProfileHandler;
@class BKTemperatureProfileHandler;
@class BKDirectometerProfileHandler;
@class BKHumidityProfileHandler;
@class BKLightProfileHandler;


/// @class      BKBlukiiDeviceContext
///
/// The BKBlukiiDeviceContext class represents the current context of one blukii device. Whenever a BKProfileLoader succeeds to load a certain profile for a given BKBlukiiDescription it will determine wheter the given BKBlukiiDescription already belongs to a BKBlukiiDeviceContext instance. If so BKProfileLoader will add the resulting BKProfileHandler for the loaded profile to that existing context. Otherwise it will create a new BKBlukiiDeviceContext and add the BKProfileHandler.
/// The basic function of a BKBlukiiDeviceContext is pretty simple. It maintains a set of BKProfileHandler objects, which result from loading a profile. After a BKProfleLoader succeeded loading the a profile it will set the delegate of the underlying CBPeripheral of the BKBlukiiDescription to the associated BKBlukiiDeviceContext. The BKBlukiiDeviceContext will now distribute the peripheral callbacks to the appropriate BKProfileHandler.
/// In applications, in which you want to use more advanced CBPeripheral features or in which you need to set the perihperals delegate to a different object, you can forward the delegate callbacks to the BKBlukiiDeviceContext by using the the following methods:
///
/// <ul><li>handleDidUpdateValueForCharacteristic:fromPeripheral:error:</li><li>handleDidWriteValueForCharacteristic:fromPeripheral:error:</li><li>handleDidUpdateSubscriptionForCharacteristic:fromPeripheral:error:</li></ul>
/// @attention  If there is a CBPeripheral, which belongs to more than one BKBlukiiDescription, and one of these BKBlukiiDescriptions alredy belongs to a BKBlukiiDeviceContext you must not load a profile for one of the other BKBlukiiDescriptions. Elsewise the concrete BKProfileLoader will not find a BKBlukiiDeviceContext, associated with the BKBlukiiDescription, and create a new context. This will lead to multiple BKBlukiiDeviceContexts for one peripheral. In such a situation peripheral callbacks may not be assigned unambiguously to one BKBlukiiDeviceContext. To ensure your application will never run into such a situation the BKBlukiiDeviceContext class will send a notifcation to all existing instances in its initializer. This notification contains the underlying CBPeripheral object of the BKBlukiiDescription, that a BKBlukiiDeviceContext instance should be created for. The receiving BKBlukiiDeviceContext instances will check if the underlying CBPeripheral object of their associated BKBlukiiDescription instances is equal to the one, included in the notification. If there is a match in one instance it will raise a BKMultipleDeviceContextsForPeripheralException.
///
/// @see        BKProfileLoader
/// @see        BKProfileHandler
/// @see        BKBlukiiDescription
SWIFT_CLASS("_TtC9blukiiKit21BKBlukiiDeviceContext")
@interface BKBlukiiDeviceContext : NSObject <CBPeripheralDelegate>

/// @property   blukiiDescription
///
/// The BKBlukiiDescription, which belongs to the BKBlukiiDeviceContext instance.
@property (nonatomic, readonly, strong) BKBlukiiDescription * _Nonnull blukiiDescription;

/// @property   batteryService
///
/// Handles the interaction with Battery Service Profile. Call loadProfileForBlukii:completeWith: on a BKBatteryServiceProfileLaoder with the BKBlukiiDescription in blukiiDescription to add an instance of that handler to a BKBlukiiDeviceContext.
///
/// @see        BKBatteryServiceProfileHandler
///
/// @seealso    BKBatteryServiceProfileLaoder
@property (nonatomic, readonly, strong) BKBatteryServiceProfileHandler * _Nullable batteryService;

/// @property   service
///
/// Handles the interaction with Service Profile. Call loadProfileForBlukii:completeWith: on a BKServiceProfileLoader with the BKBlukiiDescription in blukiiDescription to add an instance of that handler to a BKBlukiiDeviceContext.
///
/// @see        BKServiceProfileHandler
///
/// @seealso    BKServiceProfileLoader
@property (nonatomic, readonly, strong) BKServiceProfileHandler * _Nullable service;

/// @property   recording
///
/// Handles the interaction with Recording Profile. Call loadProfileForBlukii:completeWith: on a BKRecordingProfileLoader with the BKBlukiiDescription in blukiiDescription to add an instance of that handler to a BKBlukiiDeviceContext.
///
/// @see        BKRecordingProfileHandler
///
/// @seealso    BKRecordingProfileLoader
@property (nonatomic, readonly, strong) BKRecordingProfileHandler * _Nullable recording;

/// @property   accelerometer
///
/// Handles the interaction with Accelerometer Profile. Call loadProfileForBlukii:completeWith: on a BKAccelerometerProfileLoader with the BKBlukiiDescription in blukiiDescription to add an instance of that handler to a BKBlukiiDeviceContext.
///
/// @see        BKAccelerometerProfileHandler
///
/// @seealso    BKAccelerometerProfileLoader
@property (nonatomic, readonly, strong) BKAccelerometerProfileHandler * _Nullable accelerometer;

/// @property   temperature
///
/// Handles the interaction with Temperature Profile. Call loadProfileForBlukii:completeWith: on a BKTemperatureProfileLoader with the BKBlukiiDescription in blukiiDescription to add an instance of that handler to a BKBlukiiDeviceContext.
///
/// @see        BKTemperatureProfileHandler
///
/// @seealso    BKTemperatureProfileLoader
@property (nonatomic, readonly, strong) BKTemperatureProfileHandler * _Nullable temperature;

/// @property   directometer
///
/// Handles the interaction with Directometer Profile. Call loadProfileForBlukii:completeWith: on a BKDirectometerProfileLoader with the BKBlukiiDescription in blukiiDescription to add an instance of that handler to a BKBlukiiDeviceContext.
///
/// @see        BKDirectometerProfileHandler
///
/// @seealso    BKDirectometerProfileLoader
@property (nonatomic, readonly, strong) BKDirectometerProfileHandler * _Nullable directometer;

/// @property   humidity
///
/// Handles the interaction with Humidity Profile. Call loadProfileForBlukii:completeWith: on a BKHumidityProfileLoader with the BKBlukiiDescription in blukiiDescription to add an instance of that handler to a BKBlukiiDeviceContext.
///
/// @see        BKHumidityProfileHandler
///
/// @seealso    BKHumidityProfileLoader
@property (nonatomic, readonly, strong) BKHumidityProfileHandler * _Nullable humidity;

/// @property   light
///
/// Handles the interaction with Light Profile. Call loadProfileForBlukii:completeWith: on a BKLightProfileLoader with the BKBlukiiDescription in blukiiDescription to add an instance of that handler to a BKBlukiiDeviceContext.
///
/// @see        BKLightProfileHandler
///
/// @seealso    BKLightProfileLoader
@property (nonatomic, readonly, strong) BKLightProfileHandler * _Nullable light;

/// @property   altimeter
///
/// Handles the interaction with Altimeter Profile. Call loadProfileForBlukii:completeWith: on a BKAltimeterProfileLoader with the BKBlukiiDescription in blukiiDescription to add an instance of that handler to a BKBlukiiDeviceContext.
///
/// @see        BKAltimeterProfileHandler
///
/// @seealso    BKAltimeterProfileLoader
@property (nonatomic, readonly, strong) BKAltimeterProfileHandler * _Nullable altimeter;

/// @method     handleDidUpdateValueForCharacteristic:fromPeripheral:error:
///
/// Use this method to forward a call of the peripheral:didUpdateValueForCharacteristic:error: method from the CBPeripheralDelegate protocol. This might be useful in applications, which need to work directly with CoreBlueooth, where the peripheral delegates are not set to a BKBlukiiDeviceContext but should still use the BKProfileHandlers.
///
/// @param      characteristic  The CBCharacteristic from the callback.
///
/// @param      peripheral      The CBPeripheral from the callback.
///
/// @param      error           The NSError from the callback.
///
/// @attention  Make sure the calling peripheral is the one, associated with the BKBlukiiDeviceContext you call this mehtod on. Otherwise the BKBlukiiDeviceContext will raise an BKInvalidPeripheralException.
- (void)handleDidUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic fromPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;

/// @method     handleDidWriteValueForCharacteristic:fromPeripheral:error:
///
/// Use this method to forward a call of the peripheral:didWriteValueForCharacteristic:error: method from the CBPeripheralDelegate protocol. This might be useful in applications, which need to work directly with CoreBlueooth, where the peripheral delegates are not set to a BKBlukiiDeviceContext but should still use the BKProfileHandlers.
///
/// @param      characteristic  The CBCharacteristic from the callback.
///
/// @param      peripheral      The CBPeripheral from the callback.
///
/// @param      error           The NSError from the callback.
///
/// @attention  Make sure the calling peripheral is the one, associated with the BKBlukiiDeviceContext you call this mehtod on. Otherwise the BKBlukiiDeviceContext will raise an BKInvalidPeripheralException.
- (void)handleDidWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic fromPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;

/// @method     handleDidUpdateSubscriptionForCharacteristic:fromPeripheral:error:
///
/// Use this method to forward a call of the peripheral:didUpdateNotificationStateForCharacteristic:error: method from the CBPeripheralDelegate protocol. This might be useful in applications, which need to work directly with CoreBlueooth, where the peripheral delegates are not set to a BKBlukiiDeviceContext but should still use the BKProfileHandlers.
///
/// @param      characteristic  The CBCharacteristic from the callback.
///
/// @param      peripheral      The CBPeripheral from the callback.
///
/// @param      error           The NSError from the callback.
///
/// @attention  Make sure the calling peripheral is the one, associated with the BKBlukiiDeviceContext you call this mehtod on. Otherwise the BKBlukiiDeviceContext will raise an BKInvalidPeripheralException.
- (void)handleDidUpdateSubscriptionForCharacteristic:(CBCharacteristic * _Nonnull)characteristic fromPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateNotificationStateForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
@end


SWIFT_CLASS("_TtC9blukiiKit28BKDirectometerProfileHandler")
@interface BKDirectometerProfileHandler : BKEnableableProfileHandlerTemplate
- (void)handleDidUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidUpdateSubscriptionForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)updateXValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToXValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromXValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateYValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToYValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromYValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateZValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToZValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromZValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateXValueRaw:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToXValueRaw:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromXValueRaw:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateYValueRaw:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToYValueRaw:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromYValueRaw:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateZValueRaw:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToZValueRaw:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromZValueRaw:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updatePositionMonitoring:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)useCurrentPositionAsFirstMonitoringReference:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)useCurrentPositionAsSecondMonitoringReference:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)deactivatePositionMonitoring:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToPositionMonitoring:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromPositionMonitoring:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)activateHeading:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)deactivateHeading:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToHeading:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromHeading:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (nonnull instancetype)initWithBlukii:(BKBlukiiDescription * _Nonnull)blukii OBJC_DESIGNATED_INITIALIZER;
@end



/// @class  BKDirectometerProfileLoader
///
/// A concrete BKProfileLoader to load the Directometer profile.
SWIFT_CLASS("_TtC9blukiiKit27BKDirectometerProfileLoader")
@interface BKDirectometerProfileLoader : BKProfileLoaderTemplate
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




/// @class  BKFirmwareRevision
///
/// BKFirmwareRevision implements rich representation of a revision number. In opposition to a representation as a String BKFirmwareRevision holds the components, seperated by a dot, as an array with the most significant at the index zero.
///
/// The revision string "4.7.1.1" for example would result in [4, 7, 1, 1] as an array of integers.
///
/// The following operators are also overloaded to compare BKFirmwareRevision objects: ==, !=, <, > <=, >=
SWIFT_CLASS("_TtC9blukiiKit18BKFirmwareRevision")
@interface BKFirmwareRevision : NSObject

/// @property   revisionComponents
///
/// The revision components as an array of integers with the most significant component at the index zero.
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull revisionComponents;

/// Initializes a instance with a given revision as a String. The comonents will be seperated by a dot and the integer values of the resulted substrings will be stored in the revisionComponents property.
///
/// @param  string  The revision as String
- (nonnull instancetype)initWithString:(NSString * _Nonnull)string OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull _revisionComponents;
@end


SWIFT_CLASS("_TtC9blukiiKit24BKHumidityProfileHandler")
@interface BKHumidityProfileHandler : BKEnableableProfileHandlerTemplate
- (void)handleDidUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidUpdateSubscriptionForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)updateValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToValueCharacteristic:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromValueCharacteristic:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (nonnull instancetype)initWithBlukii:(BKBlukiiDescription * _Nonnull)blukii OBJC_DESIGNATED_INITIALIZER;
@end



/// @class  BKHumidityProfileLoader
///
/// A concrete BKProfileLoader to load the Humidity profile.
SWIFT_CLASS("_TtC9blukiiKit23BKHumidityProfileLoader")
@interface BKHumidityProfileLoader : BKProfileLoaderTemplate
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9blukiiKit21BKLightProfileHandler")
@interface BKLightProfileHandler : BKEnableableProfileHandlerTemplate
- (void)handleDidUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidUpdateSubscriptionForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)updateValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToValueCharacteristic:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromValueCharacteristic:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateLightMode:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateEventConfig:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)changeLightEventConfig:(uint32_t)config completion:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateEventState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToEventStateCharacteristic:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromEventStateCharacteristic:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (nonnull instancetype)initWithBlukii:(BKBlukiiDescription * _Nonnull)blukii OBJC_DESIGNATED_INITIALIZER;
@end



/// @class  BKLightProfileLoader
///
/// A concrete BKProfileLoader to load the Light profile.
SWIFT_CLASS("_TtC9blukiiKit20BKLightProfileLoader")
@interface BKLightProfileLoader : BKProfileLoaderTemplate
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@class NSData;

SWIFT_CLASS("_TtC9blukiiKit25BKRecordingProfileHandler")
@interface BKRecordingProfileHandler : BKEnableableProfileHandlerTemplate
- (void)handleDidUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidUpdateSubscriptionForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)updatePassword:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)changePasswordTo:(uint32_t)password completion:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)resetPassword:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateData:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)enableReading:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)disableReading:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateSensorConfig:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateMode:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)changeModeToInterval:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)changeModeToEvent:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)changeModeToEventAndInterval:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateInterval:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)changeIntervalTo:(uint32_t)value completion:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateDatasetLimit:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)changeDatasetLimitTo:(uint16_t)value completion:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)abrogateDatasetLimit:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateStepDetection:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)changeStepDetectionThresholdTo:(uint8_t)value completion:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateAccelerometerRange:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateAccelerometerEventConfig:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateAccelerometerEventMode:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateMagnetometerRange:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateMagnetometerThreshold:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)changeMagnetometerThresholdTo:(int16_t)threshold completion:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateMagnetometerAxisConfig:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateLightMode:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateLightEventConfig:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateTemperatureEventConfig:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateAltimeterMode:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateAltimeterEventConfig:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)parseParameterDataset:(NSData * _Nonnull)dataset;
- (nonnull instancetype)initWithBlukii:(BKBlukiiDescription * _Nonnull)blukii OBJC_DESIGNATED_INITIALIZER;
@end



/// @class  BKRecordingProfileLoader
///
/// A concrete BKProfileLoader to load the Recording profile.
SWIFT_CLASS("_TtC9blukiiKit24BKRecordingProfileLoader")
@interface BKRecordingProfileLoader : BKProfileLoaderTemplate
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9blukiiKit23BKServiceProfileHandler")
@interface BKServiceProfileHandler : BKProfileHandlerTemplate
- (void)updateMagnetometerCalibrationState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)startMagnetometerCalibration:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToMagnetometerCalibrationState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotifiy:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotifiy;
- (void)unsubscribeFromMagnetometerCalibrationState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)handleDidUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidUpdateSubscriptionForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (nonnull instancetype)initWithBlukii:(BKBlukiiDescription * _Nonnull)blukii OBJC_DESIGNATED_INITIALIZER;
@end



/// @class  BKServiceProfileLoader
///
/// A concrete BKProfileLoader to load the Service profile.
SWIFT_CLASS("_TtC9blukiiKit22BKServiceProfileLoader")
@interface BKServiceProfileLoader : BKProfileLoaderTemplate
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9blukiiKit27BKTemperatureProfileHandler")
@interface BKTemperatureProfileHandler : BKEnableableProfileHandlerTemplate
- (void)handleDidUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)handleDidUpdateSubscriptionForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)updateValue:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToValueCharacteristic:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromValueCharacteristic:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateEventConfig:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)updateEventState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)activateTemperatureMonitoring:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)deactivateTemperatureMonitoring:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (void)subscribeToEventState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion callOnNotify:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))onNotify;
- (void)unsubscribeFromEventState:(void (^ _Nonnull)(CBCharacteristic * _Nonnull characteristic, NSError * _Nullable error))completion;
- (nonnull instancetype)initWithBlukii:(BKBlukiiDescription * _Nonnull)blukii OBJC_DESIGNATED_INITIALIZER;
@end



/// @class  BKTemperatureProfileLoader
///
/// A concrete BKProfileLoader to load the Temperature profile.
SWIFT_CLASS("_TtC9blukiiKit26BKTemperatureProfileLoader")
@interface BKTemperatureProfileLoader : BKProfileLoaderTemplate
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSData (SWIFT_EXTENSION(blukiiKit))
@end

#pragma clang diagnostic pop
